from tkinter import *

root=Tk()
def showdata():
    print(i.get())
    print(j.get())
    print(k.get())
    print(p.get())
l=LabelFrame(root,text="Select Gender")
i=IntVar()
r1=Radiobutton(l,text="Male",value=1,variable=i)
r2=Radiobutton(l,text="Female",value=2,variable=i)
r1.pack()
r2.pack()
l.pack()
l1=LabelFrame(root,text="Select CASTE")
j=IntVar()
r3=Radiobutton(l1,text="SC",value=1,variable=j)
r4=Radiobutton(l1,text="ST",value=2,variable=j)
r5=Radiobutton(l1,text="OBC",value=3,variable=j)
r6=Radiobutton(l1,text="GEN",value=4,variable=j)
r3.pack()
r4.pack()
r5.pack()
r6.pack()
l1.pack()



l11=LabelFrame(root,text="Select Language")
k=StringVar()
p=StringVar()
c1=Checkbutton(l11,text="Hindi",variable=k)
c2=Checkbutton(l11,text="English",variable=p)
c1.pack()
c2.pack()
l11.pack()

btn=Button(root,text="click me",bg="yellow",fg="red",font=("Comic Sans Ms","13","bold")
           ,command=showdata)
btn.pack()
root.geometry("800x600+150+200")
root.resizable(0,0)
root.mainloop()