from turtle import *
t=Turtle()  # creating object of tutrtle class
#t.shape('turtle')
t.hideturtle()
t.speed(1)
t.pencolor('red')
t.fillcolor('yellow')
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
t.penup()

t.color('blue','yellow')
t.forward(100)
t.pendown()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
done()
