from turtle import *
t=Turtle()
s=Screen()
#s.bgcolor('yellow')
#s.bgpic('test.gif')
s.title('My Turtle')
s.setup(height=400,width=600)
t.speed(1)
t.pencolor('red')
t.fillcolor('yellow')
t.backward(100)
t.undo()
#t.reset()
#t.clear()
t.pencolor('green')
#t.write("My Turtle",font=("comic Sans Ms",25,"normal"))
t.write(("\u0915\u092c\u0942","  ","\u0915\u092c\u0942"),font=("comic Sans Ms",25,"normal"))
done()